### ISSUE TITLE
임시파일을 없애보도록하자.

### ISSUE THREAD

**Issue by Hyeonproject** [fnrkp089/CoCam#2]
임시파일을 없애보도록 .gitignore은 알거라고 생각한다.
https://www.toptal.com/developers/gitignore
이 사이트 같은것도 유용하게 사용하렴
나는 맥 임시파일 DS_Store 였나..

사실 그냥 학습하는데는 상관 없지만 그 사이에 너의 정보를 캐낼수도 있을지도.

- p.s 밥 사라..

**Comment by fnrkp089** [comment]
학습용이고 짜피 다 더미 데이터라 상관없을꺼얌
